import fs from 'node:fs';
const a=JSON.parse(fs.readFileSync(new URL('./temp-m01-hxl-frozen-return-slot-adapter-v0.1.json',import.meta.url),'utf8'));
const c=JSON.parse(fs.readFileSync(new URL('./temp-m01-hxl-frozen-return-slot-adapter-cases-v0.1.json',import.meta.url),'utf8'));
const checks=[];const check=(name,pass,detail)=>checks.push({name,pass:Boolean(pass),detail});
const slots=a.slot_contract.map(x=>x.slot);
check('original TEMP-M01 id preserved',a.task_id==='TEMP-M01',a.task_id);
check('mainline linkage preserved',a.linked_mainline_task==='K02-03-HXL-01',a.linked_mainline_task);
check('exact six unique slots',slots.length===6&&new Set(slots).size===6,slots);
check('C expected content absent',a.blindness_boundary.contains_c_expected_text===false&&a.blindness_boundary.contains_expected_page_or_column===false,a.blindness_boundary);
check('adapter cannot run before freeze',a.blindness_boundary.may_run_before_both_returns_freeze===false,a.blindness_boundary);
check('reviewer text immutable',a.blindness_boundary.may_rewrite_reviewer_text===false,a.output_per_reviewer.normalization);
check('every slot supports explicit scope or uncertainty',a.slot_contract.every(x=>x.allowed_state.some(v=>/SCOPE|OBSERVED|UNCERTAIN/.test(v))),a.slot_contract);
check('all hold states retained',["HOLD_LOCATION_CONFLICT","HOLD_TEXT_CONFLICT","HOLD_SCOPE_GAP","HOLD_UNCERTAINTY"].every(x=>a.comparison_states.includes(x)),a.comparison_states);
check('eight positive and negative cases',c.cases.length===8&&new Set(c.cases.map(x=>x.id)).size===8,c.cases);
check('cases cover blindness conflict scope uncertainty',["HOLD_BLINDNESS_BREACH","HOLD_CONFLICT","NOT_IN_REVIEW_SCOPE","HOLD_UNCERTAINTY"].every(x=>c.cases.some(y=>y.expected===x)),c.cases);
check('strict mainline unchanged',a.acceptance.mainline_before==='0/5'&&a.acceptance.mainline_after==='0/5'&&!a.acceptance.q_independent_return&&!a.acceptance.d_independent_return,a.acceptance);
const passed=checks.filter(x=>x.pass).length;
console.log(JSON.stringify({validator:'TEMP-M01-HXL-FROZEN-RETURN-SLOT-ADAPTER-VALIDATOR-V0.1',passed,total:checks.length,checks},null,2));
if(passed!==checks.length)process.exit(1);
