import fs from 'node:fs';
const a=JSON.parse(fs.readFileSync(new URL('./temp-m01-hxl-six-slot-projection-v0.1.json',import.meta.url),'utf8'));
const checks=[];const check=(name,pass,detail)=>checks.push({name,pass:Boolean(pass),detail});
const names=a.slots.map(x=>x.slot);
check('TEMP-M01 id preserved',a.task_id==='TEMP-M01',a.task_id);
check('mainline linkage explicit',a.linked_mainline_task==='K02-03-HXL-01',a.linked_mainline_task);
check('exactly six unique slots',a.slots.length===6&&new Set(names).size===6,names);
check('every slot sourced',a.slots.every(x=>x.source_refs.length>0),a.slots.map(x=>x.source_refs));
check('every slot has epistemic boundary',a.slots.every(x=>x.boundary.length>20),a.slots.map(x=>x.boundary));
check('甘忠可 attribution protected',a.slots[0].boundary.includes('甘忠可')&&a.slots[0].boundary.includes('must not be reassigned'),a.slots[0].boundary);
check('expectation not causal claim',a.slots[3].boundary.includes('not project-endorsed causal predictions'),a.slots[3].boundary);
check('mixed witness strength explicit',a.slots[4].classification==='MIXED_DIRECT_SCAN_AND_WEB_ANCHOR'&&a.slots[4].boundary.includes('editable-web'),a.slots[4]);
check('judicial narrative boundary explicit',a.slots[5].boundary.includes('not converted into modern factual labels'),a.slots[5].boundary);
check('no universal generalization',a.method_boundary.includes('not proof')&&a.cross_slot_findings[1].finding.includes('does not'),a.method_boundary);
check('blind input firewall closed',a.blindness_firewall.admissible_to_q_or_d_blind_input===false,a.blindness_firewall);
check('strict mainline unchanged',a.acceptance.mainline_before==='0/5'&&a.acceptance.mainline_after==='0/5'&&!a.acceptance.mainline_q&&!a.acceptance.mainline_d,a.acceptance);
const passed=checks.filter(x=>x.pass).length;
console.log(JSON.stringify({validator:'TEMP-M01-HXL-SIX-SLOT-PROJECTION-VALIDATOR-V0.1',passed,total:checks.length,checks},null,2));
if(passed!==checks.length)process.exit(1);
