import fs from 'node:fs';
const a=JSON.parse(fs.readFileSync(new URL('./testset-01-m02-q-c-recheck-v0.2.json',import.meta.url),'utf8'));
const checks=[];const check=(name,pass,detail)=>checks.push({name,pass:Boolean(pass),detail});
check('task id preserved',a.task_id==='M02',a.task_id);
check('C reviewer',a.reviewer_role==='C',a.reviewer_role);
check('schema-only repair',a.inputs.repair_type==='SCHEMA_ONLY'&&!a.recheck.observation_or_count_changed,a.recheck);
check('hashes 8/8',a.recheck.frozen_hashes_match==='8/8',a.recheck.frozen_hashes_match);
check('recordings 6/6',a.recheck.recording_coverage==='6/6',a.recheck.recording_coverage);
check('taxonomy 6/6',a.recheck.taxonomy_coverage==='6/6',a.recheck.taxonomy_coverage);
check('class mapping 6/6',a.recheck.allowed_class_mapping_coverage==='6/6',a.recheck.allowed_class_mapping_coverage);
check('L1 candidate-only boundary',a.recheck.evidence_level==='L1'&&a.recheck.candidate_only,a.recheck);
check('all reps UNKNOWN',a.recheck.all_rep_classifications==='UNKNOWN',a.recheck.all_rep_classifications);
check('no 30vs60/depth/quality overclaim',[a.recheck.thirty_vs_sixty,a.recheck.true_depth,a.recheck.movement_quality].every(x=>x==='NOT_ESTABLISHED'),a.recheck);
check('M02 accepted at procedural scope',a.decision.m02_acceptance&&a.decision.status==='M02_ACCEPTED_L1_CANDIDATE_ONLY',a.decision);
check('strict advances exactly once',a.decision.strict_before==='1/4'&&a.decision.strict_after==='2/4',a.decision);
check('M03/M04 remain blocked',a.dependency_state.M03==='BLOCKED_CLEAN_CONTEXT'&&a.dependency_state.M04==='BLOCKED_BY_M03',a.dependency_state);
check('D independence protected',a.dependency_state.D_independence==='PROTECTED',a.dependency_state);
const passed=checks.filter(x=>x.pass).length;
console.log(JSON.stringify({validator:'TESTSET-01-M02-Q-C-RECHECK-VALIDATOR-V0.2',passed,total:checks.length,checks},null,2));
if(passed!==checks.length)process.exit(1);
