import fs from 'node:fs';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
const checks=[];
const record=(track,name,fn)=>{try{fn();checks.push({track,name,status:'PASS'});}catch(e){checks.push({track,name,status:'FAIL',error:String(e.message)});}};
const read=p=>fs.readFileSync(p,'utf8');
const a=read('portal/assets/v02-exercise-workbench.js');
const b=read('portal/assets/v02-residence-workbench.js');
const ah=read('portal/movement.html');
const bh=read('portal/k02-board.html');
record('A01','JavaScript syntax',()=>execFileSync(process.execPath,['--check','portal/assets/v02-exercise-workbench.js']));
record('B01','JavaScript syntax',()=>execFileSync(process.execPath,['--check','portal/assets/v02-residence-workbench.js']));
record('A01','main page integration',()=>assert.ok(ah.includes('v02-exercise-workbench.js')));
record('B01','main page integration',()=>assert.ok(bh.includes('v02-residence-workbench.js')));
record('A01','exercise ID and teaching controls',()=>{for(const v of ['exercise:push-up:prototype','v02-play','v02-stop','v02-phase','v02-speed','license'])assert.ok(a.includes(v),v)});
record('A01','exercise object roles and joint motion',()=>{for(const v of ['primary','secondary','stabilizers','v02-joints','PROJECT_GUIDANCE_NOT_UPSTREAM_STANDARD'])assert.ok(a.includes(v),v)});
record('B01','residence identity and persistence',()=>{for(const v of ['zero-one.residence.v0.2','caseId','localStorage','r-export','r-import','revisions'])assert.ok(b.includes(v),v)});
record('B01','material provenance and active clarification',()=>{for(const v of ['r-material','r-source','r-confidence','r-next-question','geometryContinuity','crossLayerEquivalence'])assert.ok(b.includes(v),v)});
record('A01','explicit prototype limitation',()=>assert.ok(a.includes('未经动作专家审核')));
record('B01','explicit unverified computation limitation',()=>assert.ok(b.includes('不输出未经计算')));
const sha=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
const report={schema:'zero-one.v02.automated-check.v1',timestamp:new Date().toISOString(),sha,scope:'Static integration and syntax only. NOT public browser interaction, license audit, model runtime, or A01/B01 acceptance.',checks,passed:checks.every(c=>c.status==='PASS')};
fs.mkdirSync('artifacts/v02',{recursive:true});fs.writeFileSync('artifacts/v02/verification.json',JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify(report,null,2));
if(!report.passed)process.exitCode=1;
