import fs from 'node:fs';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import crypto from 'node:crypto';
const checks=[];
const record=(track,name,fn)=>{try{fn();checks.push({track,name,status:'PASS'});}catch(e){checks.push({track,name,status:'FAIL',error:String(e.message)});}};
const read=p=>fs.readFileSync(p,'utf8');
const a=read('portal/assets/v02-exercise-workbench.js');
const b=read('portal/assets/v02-residence-workbench.js');
const ah=read('portal/movement.html');
const bh=read('portal/k02-board.html');
const upstream=JSON.parse(read('portal/data/v02-wger-pushup.json'));
const upstreamVariant=JSON.parse(read('portal/data/v02-wger-wide-pushup.json'));
const licensedMediaVariant=JSON.parse(read('portal/data/v02-wger-clap-pushup.json'));
const residenceSample=JSON.parse(read('portal/data/v02-residence-reference-room.json'));
const archiveHome=JSON.parse(read('portal/data/v02-habs-frederick-douglass-house.json'));
const habsDepthmap=JSON.parse(read('portal/data/v02-habs-dc-97-depthmap-run.json'));
const habsRadiance=JSON.parse(read('portal/data/v02-habs-dc-97-radiance-daylight.json'));
const digest=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
record('A01','JavaScript syntax',()=>execFileSync(process.execPath,['--check','portal/assets/v02-exercise-workbench.js']));
record('B01','JavaScript syntax',()=>execFileSync(process.execPath,['--check','portal/assets/v02-residence-workbench.js']));
record('A01','main page integration',()=>assert.ok(ah.includes('v02-exercise-workbench.js')));
record('B01','main page integration',()=>assert.ok(bh.includes('v02-residence-workbench.js')));
record('A01','exercise ID and teaching controls',()=>{for(const v of ['exercise:wger:1551:push-up','v02-play','v02-stop','v02-phase','v02-speed','license'])assert.ok(a.includes(v),v)});
record('A01','exercise object roles and joint motion',()=>{for(const v of ['primary','secondary','stabilizers','v02-joints','PROJECT_GUIDANCE_NOT_UPSTREAM_STANDARD'])assert.ok(a.includes(v),v)});
record('A01','licensed upstream record imported',()=>{assert.equal(upstream.exercise.uuid,'f5b84269-18af-4464-a61f-b767cbcd81dc');assert.equal(upstream.exercise.license.shortName,'CC-BY-SA 4');assert.equal(upstream.exercise.license.author,'Settebello');for(const v of ['LICENSED_RECORD_IMPORTED','v02-wger-pushup.json','CC-BY-SA 4','Settebello'])assert.ok(a.includes(v),v)});
record('A01','licensed common variant imported',()=>{assert.equal(upstreamVariant.exercise.id,1964);assert.equal(upstreamVariant.exercise.uuid,'1842e1be-ac67-4f34-a527-4ca2b72d8e11');assert.equal(upstreamVariant.exercise.license.shortName,'CC-BY-SA 4');assert.equal(upstreamVariant.exercise.license.author,'Anon#2');for(const v of ['LICENSED_VARIANT_IMPORTED','v02-wger-wide-pushup.json','v02-load-wide','NO_MEDIA_IN_CURRENT_RECORD'])assert.ok(a.includes(v),v)});
record('A01','licensed variant media vendored and byte-valid',()=>{assert.equal(licensedMediaVariant.exercise.id,1554);assert.equal(licensedMediaVariant.exercise.mediaStatus,'LICENSED_MEDIA_VENDORED');assert.equal(fs.statSync('portal/assets/vendor/wger-clap-push-up-1554.png').size,2275146);assert.equal(digest('portal/assets/vendor/wger-clap-push-up-1554.png'),'7e6f3da44a68a285da8d987ad2ebc47f636bf17555e911d7dce0e1bb9be8ad47');execFileSync(process.execPath,['scripts/verify-png-integrity.mjs','portal/assets/vendor/wger-clap-push-up-1554.png']);for(const v of ['LICENSED_VARIANT_AND_MEDIA_VENDORED','wger-clap-push-up-1554.png','v02-load-clap'])assert.ok(a.includes(v),v)});
record('B01','residence identity and persistence',()=>{for(const v of ['zero-one.residence.v0.2','caseId','localStorage','r-export','r-import','revisions'])assert.ok(b.includes(v),v)});
record('B01','material provenance and active clarification',()=>{for(const v of ['r-material','r-source','r-confidence','r-next-question','geometryContinuity','crossLayerEquivalence'])assert.ok(b.includes(v),v)});
record('B01','field-level evidence ledger',()=>{for(const v of ['r-evidence','captureEvidence','SOURCE_MISSING','CONFIDENCE_MISSING','capturedAt'])assert.ok(b.includes(v),v)});
record('B01','real material manifest gate',()=>{for(const v of ['r-material-file','r-material-license','r-ingest-material','crypto.subtle.digest','SHA-256','materialFiles','lastMaterialSha'])assert.ok(b.includes(v),v)});
record('B01','traceable reference material loader',()=>{assert.equal(residenceSample.sampleStatus,'REFERENCE_MODEL_NOT_USER_RESIDENCE');assert.equal(residenceSample.sourceModelSha256,'513601ce6db129f984eca410c539e90eb2e5eb90c245566d461d40013cb04615');for(const v of ['r-load-sample','v02-residence-reference-room.json','sampleStatus'])assert.ok(b.includes(v),v)});
record('B01','public archive floor plan byte-valid',()=>{assert.equal(archiveHome.sampleStatus,'PUBLIC_ARCHIVE_REAL_RESIDENCE_NOT_USER_HOME');assert.equal(fs.statSync('portal/assets/vendor/habs-dc-97-sheet-2-first-floor-plan.png').size,2127568);assert.equal(digest('portal/assets/vendor/habs-dc-97-sheet-2-first-floor-plan.png'),'9dbb9f1ded1fb175cc76adaa80746c6015271f8a375a101edf3967fc5a64c315');execFileSync(process.execPath,['scripts/verify-png-integrity.mjs','portal/assets/vendor/habs-dc-97-sheet-2-first-floor-plan.png']);});
record('B01','HABS geometry and real depthmapX run',()=>{assert.equal(archiveHome.boundaries.geometryContinuity,'MANUAL_TRACE_V0_1_REQUIRES_SECOND_PERSON_CAD_REVIEW');assert.equal(archiveHome.boundaries.depthmapX,'DEPTHMAPX_0_9_1_VGA_708_POINTS');assert.equal(habsDepthmap.caseId,archiveHome.id);assert.equal(habsDepthmap.engine.binariesExecuted,true);assert.equal(habsDepthmap.output.pointCount,708);assert.equal(habsDepthmap.input.sha256,'bf8e5b0db0bfdb876a4bd205a4238d7de860ded5a67fee9841beadace4d4aaa7');assert.equal(digest(habsDepthmap.output.path),habsDepthmap.output.sha256);for(const v of ['depthmapStatus','depthmapPointCount','VGA CSV'])assert.ok(b.includes(v),v)});
record('B01','same-case real Radiance run',()=>{assert.equal(archiveHome.boundaries.radiance,'RADIANCE_6_0_2_CLEAR_SKY_80_SENSORS');assert.equal(habsRadiance.caseId,archiveHome.id);assert.equal(habsRadiance.engine.binariesExecuted,true);assert.equal(habsRadiance.engine.release,'rad6R0P2');assert.equal(habsRadiance.analysis.sensorCount,80);assert.equal(digest(habsRadiance.model.path),habsRadiance.model.sha256);assert.ok(habsRadiance.model.assumptions.includes('SOUTH_WINDOWS_MANUAL_ESTIMATE_REQUIRES_SECOND_PERSON_CAD_REVIEW'));for(const v of ['radianceStatus','radianceSensorCount','Radiance 证据','显式假设'])assert.ok(b.includes(v),v)});
record('A01','explicit prototype limitation',()=>assert.ok(a.includes('未经动作专家审核')));
record('B01','explicit unverified computation limitation',()=>assert.ok(b.includes('不输出未经计算')));
const sha=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
const report={schema:'zero-one.v02.automated-check.v1',timestamp:new Date().toISOString(),sha,scope:'Static integration and syntax only. NOT public browser interaction, license audit, model runtime, or A01/B01 acceptance.',checks,passed:checks.every(c=>c.status==='PASS')};
fs.mkdirSync('artifacts/v02',{recursive:true});fs.writeFileSync('artifacts/v02/verification.json',JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify(report,null,2));
if(!report.passed)process.exitCode=1;
